[project]
name = "llmux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.5",
    "ollama>=0.6.2",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
